import { getServerSession } from "next-auth";

import { Inter } from "next/font/google";
import "../../app/globals.css";
// import Footer from "../../components/footer/Footer"; this wouldn't work, it would give me an error. footer is in the page.jsx
import Navbar from "../../components/navbar/Navbar";
import MobileNavbar from "../../components/navbar/MobleNavbar";
import SessionProvider from "../components/SessionProvider.jsx";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const session = await getServerSession();
    return (
        <SessionProvider session={session}>
            <Navbar/>
            {/* <MobileNavbar></MobileNavbar> */}
            <div>{children}</div>
        </SessionProvider>
    );
}